const PIECES={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
let board=[],cp='w',sel=null,vmoves=[],hist=[],cap={w:[],b:[]},ep=null,castle={w:{k:1,q:1},b:{k:1,q:1}},promo=null;
function init(){return['rnbqkbnr','pppppppp','........','........','........','........','PPPPPPPP','RNBQKBNR'].map(r=>r.split(''));}
function render(){const e=document.getElementById('board');if(!e)return;e.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const s=document.createElement('div');s.className='square';s.dataset.r=r;s.dataset.c=c;const p=board[r][c];if(p!='.')s.textContent=PIECES[p];if(sel&&sel.r==r&&sel.c==c)s.classList.add('selected');const vm=vmoves.some(m=>m.r==r&&m.c==c);if(vm)s.classList.add(board[r][c]!='.'?'capture-move':'valid-move');if(hist.length){const l=hist[hist.length-1];if((l.fr==r&&l.fc==c)||(l.tr==r&&l.tc==c))s.classList.add('last-move');}if(incheck(cp)){const k=fk(cp);if(k.r==r&&k.c==c)s.classList.add('check');}s.onclick=()=>click(r,c);e.appendChild(s);}upds();rcap();}
function click(r,c){const p=board[r][c],o=p!='.'&&((cp=='w'&&p==p.toUpperCase())||(cp=='b'&&p==p.toLowerCase()));const mi=vmoves.findIndex(m=>m.r==r&&m.c==c);if(sel&&mi!=-1){mv(sel,{r,c},vmoves[mi]);return;}if(o){sel={r,c};vmoves=getm(r,c);render();}else{sel=null;vmoves=[];render();}}
function getm(r,c){const p=board[r][c];if(p=='.')return[];const m=[],iW=p==p.toUpperCase(),pc=p.toLowerCase(),d=iW?-1:1,st=iW?6:1;if(pc=='p'){if(v(r+d,c)&&board[r+d][c]=='.'){m.push({r:r+d,c,pr:r+d==0||r+d==7});if(r==st&&v(r+2*d,c)&&board[r+2*d][c]=='.')m.push({r:r+2*d,c,ep:{r:r+d,c}});}for(const dc of[-1,1]){const nc=c+dc;if(v(r+d,nc)){const t=board[r+d][nc];if(t!='.'&&iW!=(t==t.toUpperCase()))m.push({r:r+d,c:nc,cap:1,pr:r+d==0||r+d==7});if(ep&&ep.r==r+d&&ep.c==nc)m.push({r:r+d,c:nc,ep:1});}}}else if(pc=='n')[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]].forEach(([dr,dc])=>{const nr=r+dr,nc=c+dc;if(cm(r,c,nr,nc))m.push({r:nr,c:nc,cap:board[nr][nc]!='.'});});else if(pc=='b')line(r,c,[[-1,-1],[-1,1],[1,-1],[1,1]],m);else if(pc=='r')line(r,c,[[-1,0],[1,0],[0,-1],[0,1]],m);else if(pc=='q')line(r,c,[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],m);else if(pc=='k'){[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]].forEach(([dr,dc])=>{const nr=r+dr,nc=c+dc;if(cm(r,c,nr,nc))m.push({r:nr,c:nc,cap:board[nr][nc]!='.'});});const ri=castle[iW?'w':'b'];if(ri&&!incheck(iW?'w':'b')){if(ri.k&&cc(r,c,7,iW))m.push({r,c:6,cast:'k'});if(ri.q&&cc(r,c,0,iW))m.push({r,c:2,cast:'q'});}}return m.filter(x=>leg(r,c,x));}
function line(r,c,dirs,m){const p=board[r][c],iW=p==p.toUpperCase();dirs.forEach(([dr,dc])=>{for(let i=1;i<8;i++){const nr=r+dr*i,nc=c+dc*i;if(!v(nr,nc))break;const t=board[nr][nc];if(t=='.')m.push({r:nr,c:nc});else{if(iW!=(t==t.toUpperCase()))m.push({r:nr,c:nc,cap:1});break;}}});}
function cm(fr,fc,tr,tc){return v(tr,tc)&&(board[tr][tc]=='.'||(board[fr][fc]==board[fr][fc].toUpperCase())!=(board[tr][tc]==board[tr][tc].toUpperCase()));}
function cc(kr,kc,rc,iW){const d=rc>kc?1:-1;for(let c=kc+d;c!=rc;c+=d)if(board[kr][c]!='.')return false;for(let c=kc;c!=(rc>kc?6:2)+d;c+=d)if(att(kr,c,iW?'b':'w'))return false;return true;}
function v(r,c){return r>=0&&r<8&&c>=0&&c<8;}
function leg(fr,fc,m){const p=board[fr][fc],iW=p==p.toUpperCase(),sv=board[m.r][m.c];board[m.r][m.c]=p;board[fr][fc]='.';if(m.ep)board[iW?m.r+1:m.r-1][m.c]='.';const ch=incheck(iW?'w':'b');board[fr][fc]=p;board[m.r][m.c]=sv;if(m.ep)board[iW?m.r+1:m.r-1][m.c]=iW?'p':'P';return !ch;}
function mv(from,to,md){const p=board[from.r][from.c],iW=p==p.toUpperCase();if(md.cap||md.ep){const x=md.ep?(iW?'p':'P'):board[to.r][to.c];if(x!='.')iW?cap.w.push(x):cap.b.push(x);}if(md.cast){const r=from.r;if(md.cast=='k'){board[r][7]='.';board[r][5]=iW?'R':'r';}else{board[r][0]='.';board[r][3]=iW?'R':'r';}}if(md.ep)board[iW?to.r+1:to.r-1][to.c]='.';ep=md.ep||null;if(md.pr){promo={from,to};document.getElementById('promotion-modal').classList.add('show');sel=null;vmoves=[];render();return;}board[to.r][to.c]=p;board[from.r][from.c]='.';if(p.toLowerCase()=='k')castle[iW?'w':'b']={k:0,q:0};if(p.toLowerCase()=='r'){if(from.c==7)castle[iW?'w':'b'].k=0;if(from.c==0)castle[iW?'w':'b'].q=0;}hist.push({fr:from.r,fc:from.c,tr:to.r,tc:to.c,p});cp=cp=='w'?'b':'w';sel=null;vmoves=[];chend();render();}
function promote(ch){if(!promo)return;const{from,to}=promo,pp=(cp=='w'?ch.toUpperCase():ch.toLowerCase());board[to.r][to.c]=pp;board[from.r][from.c]='.';hist.push({fr:from.r,fc:from.c,tr:to.r,tc:to.c,p:pp,pr:1});document.getElementById('promotion-modal').classList.remove('show');promo=null;cp=cp=='w'?'b':'w';sel=null;vmoves=[];chend();render();}
function att(r,c,by){for(let i=0;i<8;i++)for(let j=0;j<8;j++){const p=board[i][j];if(p=='.')continue;const pw=p==p.toUpperCase();if((by=='w'&&!pw)||(by=='b'&&pw))continue;if(catt(i,j,r,c))return true;}return false;}
function catt(fr,fc,tr,tc){const p=board[fr][fc].toLowerCase(),dr=tr-fr,dc=tc-fc;switch(p){case'p':const d=board[fr][fc]=='P'?-1:1;return Math.abs(dc)==1&&dr==d;case'n':return(Math.abs(dr)==2&&Math.abs(dc)==1)||(Math.abs(dr)==1&&Math.abs(dc)==2);case'b':return Math.abs(dr)==Math.abs(dc)&&pclear(fr,fc,tr,tc);case'r':return(dr==0||dc==0)&&pclear(fr,fc,tr,tc);case'q':return(Math.abs(dr)==Math.abs(dc)||dr==0||dc==0)&&pclear(fr,fc,tr,tc);case'k':return Math.abs(dr)<=1&&Math.abs(dc)<=1;}return false;}
function pclear(fr,fc,tr,tc){const sdr=Math.sign(tr-fr),sdc=Math.sign(tc-fc);let r=fr+sdr,c=fc+sdc;while(r!=tr||c!=tc){if(board[r][c]!='.')return false;r+=sdr;c+=sdc;}return true;}
function incheck(pl){const k=fk(pl);if(!k)return false;return att(k.r,k.c,pl=='w'?'b':'w');}
function fk(pl){const k=pl=='w'?'K':'k';for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(board[r][c]==k)return{r,c};return null;}
function chend(){const c=cp;if(!hm(c)){const x=incheck(c),t=document.getElementById('game-over-title'),m=document.getElementById('game-over-message');if(x){t.textContent='Schachmatt!';m.textContent=(c=='w'?'Schwarz':'Weiß')+' gewinnt!';}else{t.textContent='Patt!';m.textContent='Unentschieden.';}document.getElementById('game-over-modal').classList.add('show');}}
function hm(pl){for(let r=0;r<8;r++)for(let c=0;c<8;c++){const p=board[r][c];if(p=='.')continue;if((pl=='w'&&p==p.toUpperCase())||(pl=='b'&&p==p.toLowerCase())){if(getm(r,c).length>0)return true;}}return false;}
function upds(msg){const e=document.getElementById('status');if(msg){e.textContent=msg;e.className='status check';return;}const x=incheck(cp);e.textContent=(cp=='w'?'Weiß':'Schwarz')+' ist am Zug'+(x?' (Schach!)':'');e.className='status '+(cp=='w'?'white-turn':'black-turn')+(x?' check':'');}
function rcap(){document.getElementById('captured-white').innerHTML=cap.w.map(p=>PIECES[p]).join('');document.getElementById('captured-black').innerHTML=cap.b.map(p=>PIECES[p]).join('');}
function closeModal(id){document.getElementById(id).classList.remove('show');}
function reset(){board=init();cp='w';sel=null;vmoves=[];hist=[];cap={w:[],b:[]};ep=null;castle={w:{k:1,q:1},b:{k:1,q:1}};promo=null;document.getElementById('promotion-modal')?.classList.remove('show');document.getElementById('game-over-modal')?.classList.remove('show');render();}
function undo(){if(hist.length==0)return;reset();}
document.addEventListener('DOMContentLoaded',()=>{board=init();render();});
